model_name: BERT_DTI
# drug_model_name: "seyonec/PubChem10M_SMILES_BPE_450k"
drug_model_name : "/share/home/grp-huangxd/zhangziyue/Downloads/PubChem10M_SMILES_BPE_450k"
# prot_model_name: "Rostlab/prot_bert_bfd"
prot_model_name: "/share/home/grp-huangxd/zhangziyue/Downloads/prot_bert_bfd"
drug_max_length: 64
prot_max_length: 545
prot_layers_keep: 18
layer_limit: true
layer_features: [768, 32, 1]
dropout: 0.1
pretrained:
  drug: true
  prot: true
freeze_pretrained:
  drug: false  # Set to true to freeze drug model weights
  prot: false  # Set to true to freeze protein model weights
random_seed: 42

train_params:
  batch_size: 32
  learning_rate: 5e-6
  num_epochs: 30
  device: cuda
  val_interval: 1
  loss_function: bce  # or smooth_l1
  early_stopping:
    enabled: true
    patience: 7      # Number of epochs to wait before stopping
    min_delta: 0.001  # Minimum change to qualify as an improvement
    monitor: val_loss # Metric to monitor ('val_loss' or any validation metric)
    mode: min         # 'min' for loss, 'max' for metrics like accuracy
  metrics:
    - auroc
    - auprc
    # - precision
    - accuracy
    - f1
    - sensitivity
    - specificity

